import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/product_model.dart';
import '../models/chat_model.dart';

class FirestoreService {
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  // Products
  Stream<List<ProductModel>> getProducts() {
    return _db.collection('products').orderBy('createdAt', descending: true).snapshots().map((snapshot) {
      return snapshot.docs.map((doc) => ProductModel.fromDocument(doc)).toList();
    });
  }

  Future<void> addProduct(ProductModel product) async {
    await _db.collection('products').add(product.toMap());
  }

  Future<void> updateProduct(ProductModel product) async {
    await _db.collection('products').doc(product.id).update(product.toMap());
  }

  Future<void> deleteProduct(String productId) async {
    await _db.collection('products').doc(productId).delete();
  }

  Future<void> updateProductStatus(String productId, bool isSold) async {
    await _db.collection('products').doc(productId).update({'isSold': isSold});
  }

  // Chats
  // Using a simplified chat structure: chats -> chatId -> messages
  // ChatId could be combination of userIds or a unique ID.
  // For simplicity: each product conversation could be a chat room. Or user-to-user.
  // Implementation: user -> chats -> contactId -> messages
  
  Stream<List<ChatMessage>> getMessages(String currentUserId, String otherUserId) {
    String chatId = getChatId(currentUserId, otherUserId);
      return _db.collection('chats')
          .doc(chatId)
          .collection('messages')
          .orderBy('timestamp', descending: false)
          .snapshots()
          .map((snapshot) => snapshot.docs.map((doc) => ChatMessage.fromDocument(doc)).toList());
  }

  Future<void> sendMessage(String currentUserId, String otherUserId, String message) async {
    String chatId = getChatId(currentUserId, otherUserId);
    ChatMessage chatMessage = ChatMessage(
        id: '', // Generated by firestore
        senderId: currentUserId,
        receiverId: otherUserId,
        message: message,
        timestamp: DateTime.now(),
    );

    await _db.collection('chats').doc(chatId).collection('messages').add(chatMessage.toMap());
    
    // Update chat document for listing
    // We store unread count for BOTH users or specifically for the receiver.
    // Let's use a Map: unreadCount: { receiverId: count++ }
    await _db.collection('chats').doc(chatId).set({
      'users': [currentUserId, otherUserId],
      'lastMessage': message,
      'timestamp': DateTime.now(),
      'unreadCount': {
        otherUserId: FieldValue.increment(1),
      }
    }, SetOptions(merge: true));
  }

  // Chat Listing & Tokens
  
  Future<void> saveUserToken(String userId, String token) async {
    await _db.collection('users').doc(userId).update({
      'fcmToken': token,
    });
  }

  Stream<List<Map<String, dynamic>>> getUserChats(String userId) {
    return _db
        .collection('chats')
        .where('users', arrayContains: userId)
        .snapshots()
        .map((snapshot) {
      final docs = snapshot.docs.map((doc) {
        final data = doc.data();
        data['id'] = doc.id;
        return data;
      }).toList();
      // Sort client-side to avoid needing a Firestore composite index
      docs.sort((a, b) {
        final aTime = a['timestamp'];
        final bTime = b['timestamp'];
        if (aTime == null && bTime == null) return 0;
        if (aTime == null) return 1;
        if (bTime == null) return -1;
        return (bTime as dynamic).compareTo(aTime as dynamic);
      });
      return docs;
    });
  }

  Future<Map<String, dynamic>?> getUserDetails(String userId) async {
    final doc = await _db.collection('users').doc(userId).get();
    return doc.data();
  }

  Future<void> markChatAsRead(String chatId, String userId) async {
    await _db.collection('chats').doc(chatId).update({
      'unreadCount.$userId': 0,
    });
  }

  String getChatId(String user1, String user2) {
    return user1.hashCode <= user2.hashCode ? '${user1}_$user2' : '${user2}_$user1';
  }
}
